# Generated by Django 5.0.13 on 2025-09-20 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('professional', 'Professional')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='business',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='matchingrule',
            name='business',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='matched_by_rule',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='paymentsource',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='paymentsource',
            name='business',
        ),
        migrations.RemoveField(
            model_name='paymentsource',
            name='source_type',
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.business')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='payments.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='MatchingRule',
        ),
        migrations.DeleteModel(
            name='Reconciliation',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
