# Generated by Django 4.2.11 on 2025-09-23 07:19

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_customer_invoice_product_payment_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Store securely!', null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='api_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Store securely!', null=True),
        ),
    ]
