# Generated by Django 5.0.13 on 2025-09-21 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='InternalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_records', to='rec.reconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_records', to='rec.reconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missing_in_internal', 'Missing in Internal'), ('missing_in_external', 'Missing in External'), ('amount_mismatch', 'Amount Mismatch')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('external_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.externalrecord')),
                ('internal_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.internalrecord')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='rec.reconciliation')),
            ],
        ),
    ]
