# Generated by Django 5.0.13 on 2025-09-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_id_column', models.CharField(max_length=100)),
                ('amount_column', models.CharField(max_length=100)),
                ('date_column', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='business.business')),
            ],
        ),
    ]
