# Generated by Django 4.2.11 on 2025-09-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('rec', '0002_columnmappingtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discrepancy',
            name='details',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='type',
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='columnmappingtemplate',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mapping_templates', to='business.business'),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='external_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.externalrecord'),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='internal_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.internalrecord'),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='externalrecord',
            name='transaction_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internalrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internalrecord',
            name='transaction_id',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TransactionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=20)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='rec.reconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_to_match', models.CharField(max_length=100)),
                ('match_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='business.business')),
            ],
        ),
    ]
