# Generated by Django 5.0.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), 
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('retention_period_days', models.PositiveIntegerField(help_text='The number of days to retain the data.')),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(help_text='The type of content this policy applies to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'ordering': ['name'],
            },
        ),
    ]
