# Generated by Django 4.2.11 on 2025-09-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('security_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataretentionpolicy',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataretentionpolicy',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='retention_period_days',
            field=models.PositiveIntegerField(),
        ),
    ]
